### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by alexandrnikitin** [Microsoft/Kafkanet#10]
Basically, it's a question that could grow to issues: is performance in focus? Any plans to work on it?

**Comment by nikuma** [comment]
The question is too vague. However, just want to point out that this project is not in active development. It works as is in production and currently only in the sustenance mode.

**Comment by alexandrnikitin** [comment]
That's what I wanted to hear. Thank you.

**Comment by ducas** [comment]
@alexandrnikitin I actually found an issue that caused quite significant performance degradation and submitted PR #37 other day. Just awaiting review…

**Comment by alexandrnikitin** [comment]
@ducas Good job! Thank you.
