### ISSUE TITLE
Any plans for a DotNetCore implementation?

### ISSUE THREAD

**Issue by raffaeler** [Microsoft/Kafkanet#12]
I am just wondering if there are any plans to convert this project (or add the support) to a dotnetcore implementation in order to support both ASPNET Core, UWP, and future Application Models.

Thank you

**Comment by skillrat** [comment]
Hello,
Sorry for the late reply. Project is maintenance mode right now so I don't think we will add .NetCore support.

Thank you!

**Comment by Neftedollar** [comment]
@riamandii maybe you can promt, what should I do to add .NetCore support?

**Comment by Reg1234** [comment]
Has anyone tried this?

https://github.com/songdongsheng/Kafka.NET 

Just curios if anyone was able to get this to work for .NetCore and Kafka

**Comment by ah-** [comment]
@Reg1234, there doesn't seem to be any actual code in that repo, all the files are pretty empty.

**Comment by Reg1234** [comment]
Thanks @ah, I saw that, don't think it's going to be too useful :-) Thanks for having a look
