### ISSUE TITLE
[PVS-Studio] V3005 - ConsumeGroupFindNewLeaderSleepIntervalMs variable assigned to itself

### ISSUE THREAD

**Issue by jthelin** [Microsoft/Kafkanet#20]
The kind people at Viva64 gave an evaluation license for PVS-Studio to try out on some OSS projects, and running it on Kafkanet source code found this problem.
http://www.viva64.com/en/pvs-studio/

https://github.com/Microsoft/Kafkanet/blob/master/src/KafkaNET.Library/Cfg/ConsumerConfiguration.cs#L127

Error V3005. The 'ConsumeGroupFindNewLeaderSleepIntervalMs' variable is assigned to itself 
http://www.viva64.com/en/d/0403/print/

I imagine that line should probably be same as Line 93 ?
``` c#
this.ConsumeGroupFindNewLeaderSleepIntervalMs = DefaultConsumeGroupFindNewLeaderSleepIntervalMs;
```

**Comment by riamandii** [comment]
thx for letting me know! 

    On Friday, March 4, 2016 1:47 PM, Jorgen Thelin <notifications@github.com> wrote:
 

 The kind people at Viva64 gave an evaluation license for PVS-Studio to try out on some OSS projects, and running it on Kafkanet source code found this problem.
http://www.viva64.com/en/pvs-studio/https://github.com/Microsoft/Kafkanet/blob/master/src/KafkaNET.Library/Cfg/ConsumerConfiguration.cs#L127Error V3005. The 'ConsumeGroupFindNewLeaderSleepIntervalMs' variable is assigned to itself 
http://www.viva64.com/en/d/0403/print/I imagine that line should probably be same as Line 93 ?this.ConsumeGroupFindNewLeaderSleepIntervalMs = DefaultConsumeGroupFindNewLeaderSleepIntervalMs;—

**Comment by jthelin** [comment]
I created PR #21 to fix this issue.

**Comment by jthelin** [comment]
PR #21 has been merged to fix this issue.
